# Generated by Django 5.2 on 2025-04-23 12:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the note', max_length=100, validators=[django.core.validators.MinLengthValidator(3)])),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('WRK', 'Work'), ('PSNL', 'Personal'), ('IDE', 'Ideas'), ('STY', 'Study')], default='PSNL', max_length=4)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
