# Generated by Django 5.2 on 2025-07-08 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seekerprofile',
            name='skills',
            field=models.CharField(blank=True, help_text='Add skills related to your profession. You can add multiple skills.'),
        ),
    ]
