# Generated by Django 5.2 on 2025-06-24 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employerprofile',
            name='account_type',
            field=models.CharField(choices=[('employer', 'Employer'), ('seeker', 'Job Seeker')], default='employer', max_length=10),
        ),
        migrations.AlterField(
            model_name='seekerprofile',
            name='account_type',
            field=models.CharField(choices=[('employer', 'Employer'), ('seeker', 'Job Seeker')], default='employer', max_length=10),
        ),
    ]
