# Generated by Django 5.2 on 2025-07-16 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_seekerprofile_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employerprofile',
            name='account_type',
            field=models.CharField(choices=[('employer', 'Employer'), ('seeker', 'Job Seeker')], max_length=10),
        ),
        migrations.AlterField(
            model_name='seekerprofile',
            name='account_type',
            field=models.CharField(choices=[('employer', 'Employer'), ('seeker', 'Job Seeker')], max_length=10),
        ),
    ]
