# Generated by Django 5.2 on 2025-06-30 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_country_phone_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employerprofile',
            name='company_size',
            field=models.CharField(choices=[('1-10', '1-10 employees'), ('11-50', '11-50 employees'), ('51-200', '51-200 employees'), ('201-500', '201-500 employees'), ('501-1000', '501-1000 employees'), ('1001+', '1001+ employees')], max_length=50),
        ),
        migrations.AlterField(
            model_name='seekerprofile',
            name='skills',
            field=models.CharField(blank=True, help_text='Comma-separated skills', max_length=512),
        ),
    ]
