# Generated by Django 5.2 on 2025-07-18 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_employerprofile_account_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='linked_accounts',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='seekerprofile',
            name='linked_accounts',
            field=models.JSONField(default=dict),
        ),
    ]
