# Generated by Django 5.2 on 2025-07-19 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_employerprofile_linked_accounts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employerprofile',
            name='linked_accounts',
        ),
        migrations.RemoveField(
            model_name='seekerprofile',
            name='linked_accounts',
        ),
    ]
