# Generated by Django 5.2 on 2025-04-12 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the ingredient', max_length=255)),
                ('ingredients', models.TextField(help_text='Comma-separated ingredients')),
                ('instructions', models.TextField(help_text='Cooking instructions')),
                ('cooking_time', models.PositiveIntegerField(help_text='Time in minutes', max_length=255)),
                ('dish_image', models.ImageField(blank=True, null=True, upload_to='dish_image/')),
            ],
        ),
    ]
