# Generated by Django 5.2 on 2025-04-12 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_secret_recipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveIntegerField(help_text='Time in minutes'),
        ),
    ]
