# Generated by Django 5.2 on 2025-07-22 23:34

import django.db.models.deletion
import jobs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        ('users', '0005_remove_employerprofile_linked_accounts_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_saved', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.jobposting')),
                ('job_saver', models.ForeignKey(default=jobs.models.get_default_user, on_delete=django.db.models.deletion.CASCADE, to='users.seekerprofile')),
            ],
        ),
    ]
