# Generated by Django 5.2 on 2025-07-23 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_savedjob'),
        ('users', '0005_remove_employerprofile_linked_accounts_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='savedjob',
            unique_together={('job', 'job_saver')},
        ),
    ]
